name: terraform ci
on:
    push:

jobs:
    tf-ci: 
        name: terraform workflow
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        steps:
            - name: checkout
              uses: actions/checkout@v7
            - name: install terraform
              uses: hashicorp/setup-terraform@v4
              with:
                terraform_version: "1.14.6"
            - name: init
              run: terraform init
            - name: plan
              run: terraform plan -out tfplan
            - name: apply
              if: ${{ github.ref_name == 'main' }}
              run: terraform apply "tfplan"
            